version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - joblink-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules  # Avoids overwriting node_modules with host version
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/joblink
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - joblink-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - joblink-network

volumes:
  mongodb_data:

networks:
  joblink-network:
    driver: bridge 